#!/bin/bash

set +e

WWWDATAUSER=$(id www-data)
if [ $? -eq 1 ]; then
    echo "Creating www-data user"
    adduser -S www-data
    addgroup www-data
    addgroup www-data www-data
fi

rc-service nginx stop
rc-update del nginx default

exit 0