---
kind: pipeline
type: docker
name: default

environment:
  DEFAULT_VERSION: 1.18.0
  DEFAULT_REVISION: 1

steps:
  - name: version
    image: charlesportwoodii/alpine:3.11-base
    commands:
      - if [ -n "${DRONE_TAG}" ]; then echo "VERSION=$(cut -d '-' -f 1 <<< \"$DRONE_TAG\")" > .envs; echo "RELEASEVER=$(cut -d '-' -f 2 <<< \"$DRONE_TAG\")" >> .envs; else echo "VERSION=$DEFAULT_VERISON" > .envs; echo "RELEASEVER=$DEFAULT_REVISION" >> .envs; fi
      - cat .envs

    