---
kind: pipeline
type: docker
name: default

environment:
  DEFAULT_VERSION: 1.18.0
  DEFAULT_REVISION: 1

steps:
  - name: version
    image: ubuntu:latest
    commands:
      - /bin/bash -c "if [ -n \"$DRONE_TAG\" ]; then echo \"VERSION=$(cut -d '-' -f 1 <<< $DRONE_TAG)\" | tee -a .envs; echo \"RELEASEVER=$(cut -d '-' -f 2 <<< $DRONE_TAG)\" | tee -a .envs; else echo \"VERSION=$DEFAULT_VERSION\" | tee -a .envs; echo \"RELEASEVER=$DEFAULT_REVISION\" | tee -a .envs; fi"
      - cat .envs

    