---
kind: pipeline
type: docker
name: default

environment:
  DEFAULT_VERSION: 1.18.0
  DEFAULT_REVISION: 1

steps:
  - name: preflight
    image: ubuntu:latest
    commands:
      - /bin/bash version.sh
      - echo $(uname -s):$(uname -r):$(uname -v):$(uname -m)
      - mkdir -p build/deb
      - mkdir -p build/alpine
      - mkdir -p build/rpm
  - name: Build Focal (Ubuntu 20.04)
    image: charlesportwoodii/ubuntu:20.04-build
    depends_on:
      - preflight
    environment:
      BUILD_IMAGE: focal
      BUILD_OS: Ubuntu
      BUILD_OS_VERSION: "20.04"
    commands:
      - bash -lc "make build fpm_debian OPENSSL_CI_HACK=1"
      - mkdir -p build/deb/$BUILD_IMAGE
      - mv *$BUILD_IMAGE*.deb build/deb/$BUILD_IMAGE/
  
  
