---
kind: pipeline
type: docker
name: default

environment:
  DEFAULT_VERSION: 1.18.0
  DEFAULT_REVISION: 1

steps:
  - name: Extract Version
    image: ubuntu:latest
    commands:
      - /bin/bash version.sh
  - name: Build Focal (Ubuntu 20.04)
    image: charlesportwoodii/ubuntu:20.04-build
    depends_on:
      - "Extract Version"
    commands:
      - bash -lc "make build fpm_debian"
