---
kind: pipeline
type: docker
name: default

environment:
  DEFAULT_VERSION: 1.18.0
  DEFAULT_REVISION: 1

steps:
  - name: version
    image: ubuntu:latest
    commands:
      - /bin/bash version.sh
      - cat .envs

    