---
kind: pipeline
type: docker
name: build-amd64

environment:
  DEFAULT_VERSION: 1.21.1
  DEFAULT_REVISION: 1

platform:
  arch: amd64

steps:
  - name: preflight
    image: python:3-alpine
    commands:
      - pip3 install semver
      - python3 genenv
      - echo $(uname -s):$(uname -r):$(uname -v):$(uname -m)
      - mkdir -p build/deb
      - mkdir -p build/alpine
      - mkdir -p build/rpm
  - name: focal
    image: charlesportwoodii/ubuntu:20.04-build
    depends_on:
      - preflight
    environment:
      BUILD_IMAGE: focal
      BUILD_OS: Ubuntu
      BUILD_OS_VERSION: "20.04"
    commands:
      - bash -lc "make build fpm_debian OPENSSL_CI_HACK=1"
      - mkdir -p build/deb/$BUILD_IMAGE
      - mv *$BUILD_IMAGE*.deb build/deb/$BUILD_IMAGE/
  - name: "alpine3.11"
    image: charlesportwoodii/alpine:3.11-build
    depends_on:
      - preflight
    environment:
      BUILD_IMAGE: "alpine3.11"
      BUILD_OS: Alpine
      BUILD_OS_VERSION: "3.11"
    commands:
      - bash -lc "apk add --no-cache luajit-2.1"
      - bash -lc "make clean base openssl pcre nginx fpm_alpine OPENSSL_CI_HACK=1"
      - mkdir -p build/alpine/v$BUILD_OS_VERSION/main/x86_64
      - mv *.apk build/alpine/v$BUILD_OS_VERSION/main/x86_64
  - name: "alpine3.14"
    image: charlesportwoodii/alpine:3.14-build
    depends_on:
      - preflight
    environment:
      BUILD_IMAGE: "alpine3.14"
      BUILD_OS: Alpine
      BUILD_OS_VERSION: "3.14"
    commands:
      - bash -lc "apk add --no-cache luajit-2.1"
      - bash -lc "make clean base openssl pcre nginx fpm_alpine OPENSSL_CI_HACK=1"
      - mkdir -p build/alpine/v$BUILD_OS_VERSION/main/x86_64
      - mv *.apk build/alpine/v$BUILD_OS_VERSION/main/x86_64
  - name: deploy
    image: plugins/s3-sync
    when:
      event:
        - tag
    depends_on:
      - focal
      - "alpine3.11"
      - "alpine3.14"
    settings:
      bucket:
        from_secret: AWS_BUCKET
      endpoint:
        from_secret: AWS_HOST
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      source: build/
      path_style: true
      target: /
      delete: false
      acl:
        "*": public-read
  - name: update-apt-packages
    depends_on:
      - deploy
    when:
      event:
        - tag
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      key:
        from_secret: SSH_KEY
      port: 22
      script:
        - /usr/local/bin/update-apt-packages
  - name: update-alpine-packages
    depends_on:
      - deploy
    when:
      event:
        - tag
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      key:
        from_secret: SSH_KEY
      port: 22
      script:
        - /usr/local/bin/update-alpine-packages x86_64

---
kind: pipeline
type: docker
name: build-arm64

environment:
  DEFAULT_VERSION: 1.21.1
  DEFAULT_REVISION: 1

platform:
  arch: arm64

steps:
  - name: preflight
    image: python:3-alpine
    commands:
      - pip3 install semver
      - python3 genenv
      - echo $(uname -s):$(uname -r):$(uname -v):$(uname -m)
      - mkdir -p build/deb
      - mkdir -p build/alpine
      - mkdir -p build/rpm
  - name: focal
    image: charlesportwoodii/ubuntu:20.04-build
    depends_on:
      - preflight
    environment:
      BUILD_IMAGE: focal
      BUILD_OS: Ubuntu
      BUILD_OS_VERSION: "20.04"
    commands:
      - bash -lc "make build fpm_debian OPENSSL_CI_HACK=1"
      - mkdir -p build/deb/$BUILD_IMAGE
      - mv *$BUILD_IMAGE*.deb build/deb/$BUILD_IMAGE/
  - name: "alpine3.14"
    image: charlesportwoodii/alpine:3.14-build
    depends_on:
      - preflight
    environment:
      BUILD_IMAGE: "alpine3.14"
      BUILD_OS: Alpine
      BUILD_OS_VERSION: "3.14"
    commands:
      - bash -lc "apk add --no-cache luajit-2.1"
      - bash -lc "make clean base openssl pcre nginx fpm_alpine OPENSSL_CI_HACK=0"
      - mkdir -p build/alpine/v$BUILD_OS_VERSION/main/aarch64
      - mv *.apk build/alpine/v$BUILD_OS_VERSION/main/aarch64
  - name: deploy
    image: plugins/s3-sync
    when:
      event:
        - tag
    depends_on:
      - "alpine3.14"
    settings:
      bucket:
        from_secret: AWS_BUCKET
      endpoint:
        from_secret: AWS_HOST
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      source: build/
      path_style: true
      target: /
      delete: false
      acl:
        "*": public-read
  - name: update-alpine-packages
    depends_on:
      - deploy
    when:
      event:
        - tag
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      key:
        from_secret: SSH_KEY
      port: 22
      script:
        - /usr/local/bin/update-alpine-packages aarch64

---
kind: pipeline
type: docker
name: deploy

depends_on:
  - build-amd64
  - build-arm64

platform:
  arch: amd64

steps:
  - name: preflight
    image: python:3-alpine
    commands:
      - pip3 install semver
      - python3 genenv
      - echo $(uname -s):$(uname -r):$(uname -v):$(uname -m)
      - mkdir -p build/deb
      - mkdir -p build/alpine
      - mkdir -p build/rpm
  - name: docker
    depends_on:
      - preflight
    when:
      event:
        - tag
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.6.0/buildx-v0.6.0.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build --push --platform linux/arm64,linux/amd64 $(for i in $(cat .envs); do echo -n "--build-arg $i "; done) -t charlesportwoodii/nginx:$(head -n1 .envs | sed "s/VERSION=//") -t charlesportwoodii/nginx:$(tail -n1 .envs | sed "s/SHORT_VERSION=//") --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
