# docker-compose.yml

version: '3.3'
services:
    trusty: 
        image: charlesportwoodii/trusty:build
        command: bash -lc "make build fpm_debian VERISON=$VERSION RELEASEVER=$RELEASEVER"
        volumes: 
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    xenial:
        image: charlesportwoodii/xenial:build
        command: bash -lc "make build fpm_debian VERISON=$VERSION RELEASEVER=$RELEASEVER"
        volumes: 
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    centos7:
        image: charlesportwoodii/centos7:build
        command: bash -lc "make build fpm_rpm VERISON=$VERSION RELEASEVER=$RELEASEVER"
        volumes: 
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    rhel7:
        image: charlesportwoodii/rhel7:build
        command: bash -lc "make build fpm_rpm VERISON=$VERSION RELEASEVER=$RELEASEVER"
        volumes: 
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    alpine3.6:
        image: charlesportwoodii/alpine3.6:build
        command: bash -lc "make build fpm_alpine VERISON=$VERSION RELEASEVER=$RELEASEVER"
        volumes: 
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
