#!/bin/bash

set +e
echo "Stopping Nginx"

CODENAME=$(lsb_release --codename | cut -f2)
if [ $CODENAME = "xenial" ]
then
	systemctl stop nginx.service
	systemctl disable nginx.service
else
	$(which service) nginx stop
fi

exit 0
