#!/bin/bash
make install
CODENAME=$(lsb_release --codename | cut -f2)
if [ $CODENAME = "xenial" ]
then
	cp nginx.service /lib/systemd/system/nginx.service
	systemctl enable nginx.service
else
	cp init-nginx /etc/init.d/nginx
	chmod a+x /etc/init.d/nginx
fi

cp conf/ssl.conf /etc/nginx/conf/ssl.conf
cp conf/fastcgi.conf /etc/nginx/conf/fastcgi.conf.default
cp conf/fastcgi_params /etc/nginx/conf/fastcgi_params.default
cp conf/koi-utf /etc/nginx/conf
cp conf/koi-win /etc/nginx/conf
cp conf/mime.types /etc/nginx/conf
cp conf/nginx.conf /etc/nginx/conf/nginx.conf.default
cp conf/scgi_params /etc/nginx/conf
cp conf/uwsgi_params /etc/nginx/conf
cp conf/win-utf /etc/nginx/conf

mkdir -p /etc/nginx/client_body_temp 
mkdir -p /etc/nginx/conf/conf.d
mkdir -p /etc/nginx/fastcgi_temp
mkdir -p /etc/nginx/html
mkdir -p /etc/nginx/proxy_temp
mkdir -p /etc/nginx/scgi_temp
mkdir -p /etc/nginx/uwsgi_temp

mkdir -p /var/log/nginx

ldconfig
