#!/bin/bash

set +e

if [ ! -f /etc/nginx/conf/nginx.conf ]; then
	$(which cp) /etc/nginx/conf/nginx.conf.default /etc/nginx/conf/nginx.conf
fi

if [ ! -f /etc/nginx/conf/fastcgi.conf ]; then
	$(which cp) /etc/nginx/conf/fastcgi.conf.default /etc/nginx/conf/fastcgi.conf
fi

if [ ! -f /etc/nginx/conf/fastcgi_params.conf ]; then
	$(which cp) /etc/nginx/conf/fastcgi_params.default /etc/nginx/conf/fastcgi_params
fi

if [ ! -d /etc/nginx/conf/conf.d ]; then
	$(which mkdir) -p /etc/nginx/conf/conf.d
fi

if [ ! -d /etc/nginx/conf/ssl ]; then
	$(which mkdir) -p /etc/nginx/conf/ssl
fi

if [ ! -f /etc/nginx/conf/modules.conf ]; then
	$(which cp) /etc/nginx/conf/modules.conf /etc/nginx/conf/modules.conf;
fi

if [ ! -f /etc/nginx/conf/ssl/dhparams.pem ]; then
	openssl dhparam -out /etc/nginx/conf/ssl/dhparams.pem 2048
fi

if [ ! -f /usr/bin/nginx ]; then
	ln -s /usr/local/nginx/sbin/nginx /usr/bin/nginx
fi

systemctl enable nginx.service
systemctl start nginx.service

exit 0
