#!/bin/bash

set +e

which lsb_release
if [ "$?" == 0 ]
then
        CODENAME=$(lsb_release --codename | cut -f2)
        if [ "$CODENAME" = "precise" ] || [ "$codename" = "trusty" ]
        then
	    $(which service) nginx stop
	    rm -rf /etc/init.d/nginx
        else
            systemctl stop nginx.service
	        systemctl disable nginx.service
	        rm -rf /lib/systemd/system/nginx.service
        fi
else
    systemctl stop nginx.service
    systemctl disable nginx.service
    rm -rf /lib/systemd/system/nginx.service
fi

exit 0
